# https://stackoverflow.com/questions/41094864/is-it-possible-to-write-ansible-hosts-inventory-files-in-yaml
all:
  children:
    local:
      hosts:
        localhost:
          # RAM is 16 GB
          swap_size: 16384
